disabled = false
languageCode = "ja"
languageName = "日本語"
weight = 1
title = "sigmarho"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/sigmarho_logo_white.png"
  description = "sigmarho's website"

 [params.author]
  name = "sigmarho"
  image = "img/sigmarho_self-portrait.jpg"
  imageQuality = 96
#  headline = ""
  bio = "graduate student /quantum information theory"
  links = [
    { misskey = "https://misskey.io/@semolina_pilchard" },
    { x-twitter = "https://x.com/sigmarho_2" },
    { youtube = "https://www.youtube.com/channel/UCgvmqOB0FCmeuw6D_Ma3jxA" },
  ]
